cmake_minimum_required(VERSION 4.1)
project(cpp_daily_challenges)

set(CMAKE_CXX_STANDARD 20)

add_executable(cpp_daily_challenges
        solutions/easy/task01.cpp
        solutions/easy/task02.cpp
        solutions/hackerrank/inputoutput01.cpp
        solutions/easy/task03.cpp
        solutions/easy/task04.cpp
        solutions/easy/task05.cpp
        solutions/easy/task06.cpp
        "solutions/other/BMI calculator.cpp"
        solutions/easy/task07.cpp
        solutions/easy/task07p2.cpp
        solutions/easy/task08.cpp
        solutions/easy/task09.cpp
        solutions/easy/task10.cpp
        solutions/easy/task11.cpp
        solutions/easy/task12.cpp
        solutions/easy/task12.2.cpp
        solutions/easy/task13.cpp
        "solutions/easy/task 14.cpp"
        solutions/easy/task15.cpp
        solutions/easy/task16.cpp
        solutions/easy/task17.cpp
        solutions/easy/task18.cpp
        solutions/easy/task19.cpp
        solutions/easy/task20.cpp
        solutions/easy/task21.cpp
        solutions/easy/task1.cpp
        solutions/easy/task2.cpp
        solutions/easy/task1.1.cpp
        "solutions/easy/tasks1.cpp"
        solutions/easy/task2.1.cpp
        solutions/easy/task3.1.cpp
        solutions/easy/tasks3.cpp
        solutions/easy/task4.1.cpp
        solutions/hackerrank/forloop02.cpp
        solutions/hackerrank/condtionalstatments03.cpp
        solutions/hackerrank/Forloop.cpp
        solutions/hackerrank/Functions.cpp
)
